### ISSUE TITLE
--prefix-routes causes panic

### ISSUE THREAD

**Issue by jademcgough** [influxdata/chronograf#1665]
```
./chronograf --basepath=http://localhost:8888 --prefix-routes
panic: path must begin with '/' in path 'http:/localhost:8888/swagger.json'

goroutine 1 [running]:
panic(0x5c3220, 0xc4200e3da0)
	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:500 +0x1a1
github.com/influxdata/chronograf/vendor/github.com/bouk/httprouter.(*Router).Handler(0xc420015440, 0x6c0a41, 0x3, 0xc42010c7b0, 0x21, 0xa4c720, 0xc42010c6f0)
	/Users/jadems/Workspace/src/github.com/influxdata/chronograf/vendor/github.com/bouk/httprouter/router.go:200 +0x26f
github.com/influxdata/chronograf/vendor/github.com/bouk/httprouter.(*Router).Handle(0xc420015440, 0x6c0a41, 0x3, 0xc42010c7b0, 0x21, 0xc42010c6f0)
	/Users/jadems/Workspace/src/github.com/influxdata/chronograf/vendor/github.com/bouk/httprouter/router.go:195 +0x69
github.com/influxdata/chronograf/vendor/github.com/bouk/httprouter.(*Router).GET(0xc420015440, 0xc42010c7b0, 0x21, 0xc42010c6f0)
	/Users/jadems/Workspace/src/github.com/influxdata/chronograf/vendor/github.com/bouk/httprouter/router.go:153 +0x5e
github.com/influxdata/chronograf/server.(*MountableRouter).GET(0xc420108b00, 0x6c4f91, 0xd, 0xc42010c6f0)
	/Users/jadems/Workspace/src/github.com/influxdata/chronograf/server/mountable_router.go:28 +0xc4
github.com/influxdata/chronograf/server.NewMux(0xa54580, 0xc4200320a0, 0x0, 0x7fff5fbff9a0, 0x15, 0x1, 0xa52c60, 0xc4200153c0, 0xc420015400, 0x5, ...)
	/Users/jadems/Workspace/src/github.com/influxdata/chronograf/server/mux.go:70 +0x4c5
github.com/influxdata/chronograf/server.(*Server).Serve(0xc4200f6000, 0xa52a60, 0xc4200122e0, 0x0, 0x0)
	/Users/jadems/Workspace/src/github.com/influxdata/chronograf/server/server.go:316 +0xcda
main.main()
	/Users/jadems/Workspace/src/github.com/influxdata/chronograf/cmd/chronograf/main.go:46 +0x1b4
```

**Comment by jademcgough** [comment]
Closing this - I was using basepath incorrectly

**Comment by jaredscheib** [comment]
For future reference: `basepath` expects an edge of a directory tree, such as `/bob`, rather than an absolute path. Then, if used in conjunction with `--prefix-routes`, the server will do the magic to make the homepage http://localhost:8888/bob`, and use `/bob` as a prefix for all routes.
