### ISSUE TITLE
Bolt DB error: panic: index out of range

### ISSUE THREAD

**Issue by spiffytech** [influxdata/chronograf#2712]
My Chronograf install suddenly fell over with this message. How can I fix it?

Chronograf 1.4.0.1

```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/influxdata/chronograf/vendor/github.com/boltdb/bolt.(*Cursor).keyValue(0xc420057380, 0x1190d58, 0x0, 0x0, 0x1, 0xc420124000, 0x0, 0x1)
       /root/go/src/github.com/influxdata/chronograf/vendor/github.com/boltdb/bolt/cursor.go:354 +0x19e
github.com/influxdata/chronograf/vendor/github.com/boltdb/bolt.(*Cursor).First(0xc420057380, 0x0, 0x0, 0x1190d58, 0x0, 0x0, 0x9262df)
       /root/go/src/github.com/influxdata/chronograf/vendor/github.com/boltdb/bolt/cursor.go:44 +0x155
github.com/influxdata/chronograf/vendor/github.com/boltdb/bolt.(*Bucket).ForEach(0xc420063380, 0xc4200573e0, 0x8, 0x8)
       /root/go/src/github.com/influxdata/chronograf/vendor/github.com/boltdb/bolt/bucket.go:360 +0xb5
github.com/influxdata/chronograf/bolt.(*DashboardsStore).All.func1(0xc4200ee540, 0xb460d8, 0xc4200ee540)
       /root/go/src/github.com/influxdata/chronograf/bolt/dashboards.go:71 +0x93
github.com/influxdata/chronograf/vendor/github.com/boltdb/bolt.(*DB).View(0xc42010c1e0, 0xc420057470, 0x0, 0x0)
       /root/go/src/github.com/influxdata/chronograf/vendor/github.com/boltdb/bolt/db.go:626 +0x9f
github.com/influxdata/chronograf/bolt.(*DashboardsStore).All(0xc4200d3da0, 0xef7140, 0xc420010200, 0x0, 0x0, 0xc4200ee460, 0x0, 0x0)
       /root/go/src/github.com/influxdata/chronograf/bolt/dashboards.go:75 +0x7a
github.com/influxdata/chronograf/bolt.(*DashboardsStore).Migrate(0xc4200d3da0, 0xef7140, 0xc420010200, 0x0, 0xc42010c1e0)
       /root/go/src/github.com/influxdata/chronograf/bolt/dashboards.go:53 +0x43
github.com/influxdata/chronograf/bolt.(*Client).Open(0xc42007a8a0, 0xef7140, 0xc420010200, 0xc420101610, 0xc420101600)
       /root/go/src/github.com/influxdata/chronograf/bolt/client.go:79 +0x115
github.com/influxdata/chronograf/server.openService(0xef7140, 0xc420010200, 0xc42001400a, 0x24, 0xeed580, 0xc42011e000, 0xeed5c0, 0xc42011e030, 0xeed540, 0xc42011e060, ...)
       /root/go/src/github.com/influxdata/chronograf/server/server.go:400 +0x2d6
github.com/influxdata/chronograf/server.(*Server).Serve(0xc420108000, 0xef7140, 0xc420010200, 0x0, 0x0)
       /root/go/src/github.com/influxdata/chronograf/server/server.go:302 +0x75d
main.main()
       /root/go/src/github.com/influxdata/chronograf/cmd/chronograf/main.go:46 +0x1c4
```

**Comment by jaredscheib** [comment]
Hi @spiffytech, would you mind providing the server logs just before this panic?

cc @desa

**Comment by spiffytech** [comment]
Sorry, I don't have any more logs :( Docker Swarm removed the old containers and their logs when the chronograf process terminated.

This happened sometime overnight. I was on 1.3, and upgraded to 1.4 this morning after seeing the issue in case it would help.

How else can I help you debug this?

**Comment by jaredscheib** [comment]
I see, so to confirm, it sounds like you were on some version of 1.3 (which, if you know?), and upon seeing the above panic, upgraded to 1.4 and still got the panic?

**Comment by spiffytech** [comment]
Yep, that's correct. It was Chronograf 1.3.10.0.

**Comment by jaredscheib** [comment]
Thanks for the info. I think @desa or @goller may have insight into this issue.

**Comment by jaredscheib** [comment]
@spiffytech Do you happen to recall whether it was the case that you got the same `panic: runtime error: index out of range` while still on 1.3.10.0? And do you recall if it was in the same error trace context of (what appears here to be) migration? I wonder if it was a different panic or different error trace context since you mentioned that it originally happened prior to upgrading, in which case I'm not sure why there would be a migration. This would help us in diagnosing, if you recall either of these. Thanks again~

**Comment by spiffytech** [comment]
I did get the error on 1.13.10.0. The error was the same, and it was not in the context of a migration.

**Comment by goller** [comment]
Hi @spiffytech, would you be able to send me your chronograf-v1.db via email? I'm having a hard time reproducing this but want to solve it right away.

My email is my first name  at influxdb.com

**Comment by goller** [comment]
@spiffytech Do you still happen to be having this panic?  Seeing a panic really worries me!  I would love to get your database to try to reproduce.

**Comment by nhaugo** [comment]
@spiffytech additionally we can set up a sftp login for you

**Comment by russorat** [comment]
closing due to lack of activity
