### ISSUE TITLE
 Chronograf (1.7.0) Cannot read property 'queryID' of undefined

### ISSUE THREAD

**Issue by gshif** [influxdata/chronograf#4613]
```
TypeError: Cannot read property 'queryID' of undefined
    at http://localhost:8888/src.83c91924.js:3802:7875
    at Array.map (<anonymous>)
    at x.get (http://localhost:8888/src.83c91924.js:3802:7850)
    at x.value (http://localhost:8888/src.83c91924.js:3802:5888)
    at ia (http://localhost:8888/src.83c91924.js:716:58760)
    at aa (http://localhost:8888/src.83c91924.js:716:58602)
    at fa (http://localhost:8888/src.83c91924.js:716:60859)
    at Wa (http://localhost:8888/src.83c91924.js:716:74893)
    at Va (http://localhost:8888/src.83c91924.js:716:75239)
    at wi (http://localhost:8888/src.83c91924.js:716:79907)
```

**Comment by gshif** [comment]
I will get this info as soon as my test environment is up and running

**Comment by gshif** [comment]
I am not able to repro with the latest master. Closing
