### ISSUE TITLE
 Chronograf (1.7.1) Expected number or array but got string:  [MgmtSrvr] Node 3: Global checkpoint 29127442 started.

### ISSUE THREAD

**Issue by awaybreaktoday** [influxdata/chronograf#4802]
```Error: Expected number or array but got string:  [MgmtSrvr] Node 3: Global checkpoint 29127442 started.
    at j (https://influxer.apps.syntec.co.uk:8888/src.3a7a1bfb.js:3146:1898)
    at W.parseArray_ (https://influxer.apps.syntec.co.uk:8888/src.3a7a1bfb.js:3146:31911)
    at W.start_ (https://influxer.apps.syntec.co.uk:8888/src.3a7a1bfb.js:3146:35574)
    at W.updateOptions (https://influxer.apps.syntec.co.uk:8888/src.3a7a1bfb.js:3146:36541)
    at f.value (https://influxer.apps.syntec.co.uk:8888/src.3a7a1bfb.js:3206:4878)
    at xi (https://influxer.apps.syntec.co.uk:8888/src.3a7a1bfb.js:716:84251)
    at wi (https://influxer.apps.syntec.co.uk:8888/src.3a7a1bfb.js:716:79945)
    at ki (https://influxer.apps.syntec.co.uk:8888/src.3a7a1bfb.js:716:79561)
    at Ha (https://influxer.apps.syntec.co.uk:8888/src.3a7a1bfb.js:716:78073)
    at Object.enqueueSetState (https://influxer.apps.syntec.co.uk:8888/src.3a7a1bfb.js:716:47062)```

**Comment by russorat** [comment]
@awaybreaktoday thanks! could you describe what you were doing when you saw this issue?
