### ISSUE TITLE
 Chronograf (1.7.3) Invalid size returned for cell 4 of value NaN

### ISSUE THREAD

**Issue by bsculley** [influxdata/chronograf#4830]
```Error: Invalid size returned for cell 4 of value NaN
   at value (http://192.168.1.126:8888/src.85d3bd0b.js:2821:1405)
   at value (http://192.168.1.126:8888/src.85d3bd0b.js:2821:2692)
   at value (http://192.168.1.126:8888/src.85d3bd0b.js:2825:2264)
   at value (http://192.168.1.126:8888/src.85d3bd0b.js:2896:12871)
   at value (http://192.168.1.126:8888/src.85d3bd0b.js:2896:11092)
   at ia (http://192.168.1.126:8888/src.85d3bd0b.js:716:58745)
   at aa (http://192.168.1.126:8888/src.85d3bd0b.js:716:58595)
   at fa (http://192.168.1.126:8888/src.85d3bd0b.js:716:60852)
   at Wa (http://192.168.1.126:8888/src.85d3bd0b.js:716:74887)
   at Va (http://192.168.1.126:8888/src.85d3bd0b.js:716:75236)```

**Comment by bsculley** [comment]
I would love to, but I was just getting started with Influx when this happened and I'm not sure what caused it.  I do recall that the result area was blank except for the work "done" in the upper left corner, preceded by some other text that was chopped off.  "done" turned out to be a link which took me to this page when I clicked it.
