### ISSUE TITLE
 Chronograf (1.7.3) Cannot read property 'trim' of null

### ISSUE THREAD

**Issue by phanirajgoutham** [influxdata/chronograf#4836]
```TypeError: Cannot read property 'trim' of null
    at Object.children (https://chronograf.alphonso.tv:8888/src.85d3bd0b.js:3296:5333)
    at w.value (https://chronograf.alphonso.tv:8888/src.85d3bd0b.js:3266:6471)
    at ia (https://chronograf.alphonso.tv:8888/src.85d3bd0b.js:716:58760)
    at aa (https://chronograf.alphonso.tv:8888/src.85d3bd0b.js:716:58602)
    at fa (https://chronograf.alphonso.tv:8888/src.85d3bd0b.js:716:60859)
    at Wa (https://chronograf.alphonso.tv:8888/src.85d3bd0b.js:716:74893)
    at Va (https://chronograf.alphonso.tv:8888/src.85d3bd0b.js:716:75239)
    at wi (https://chronograf.alphonso.tv:8888/src.85d3bd0b.js:716:79907)
    at ki (https://chronograf.alphonso.tv:8888/src.85d3bd0b.js:716:79561)
    at Ha (https://chronograf.alphonso.tv:8888/src.85d3bd0b.js:716:78073)```

**Comment by russorat** [comment]
@phanirajgoutham could you add reproduction steps to help us investigate?
