### ISSUE TITLE
 Chronograf (1.7.0) Cannot read property 'dataType' of undefined

### ISSUE THREAD

**Issue by e-dard** [influxdata/chronograf#4869]
```TypeError: Cannot read property 'dataType' of undefined
    at E.t.lineGraph (http://chronograf.internal/src.e3d80458.js:3296:3676)
    at Object.children (http://chronograf.internal/src.e3d80458.js:3296:6070)
    at w.value (http://chronograf.internal/src.e3d80458.js:3266:6471)
    at ia (http://chronograf.internal/src.e3d80458.js:716:58760)
    at aa (http://chronograf.internal/src.e3d80458.js:716:58602)
    at fa (http://chronograf.internal/src.e3d80458.js:716:60859)
    at Wa (http://chronograf.internal/src.e3d80458.js:716:74893)
    at Va (http://chronograf.internal/src.e3d80458.js:716:75239)
    at wi (http://chronograf.internal/src.e3d80458.js:716:79907)
    at ki (http://chronograf.internal/src.e3d80458.js:716:79561)```

**Comment by chnn** [comment]
Hi @e-dard, do you remember what you were doing when this error was thrown? Any steps we can take to reproduce it?

**Comment by docmerlin** [comment]
This happened to me when a flux query returned a 500.

**Comment by chnn** [comment]
@docmerlin Do you have the flux query you ran? 

I've tried a flux query that returns a 500 but haven't been able to reproduce yet.

**Comment by docmerlin** [comment]
Sorry I do not, the crash was pretty random.

**Comment by chnn** [comment]
Ok no worries. I suspect the issue is that we are attempting to parse a Flux error response as a successful response. If you experience the crash in the future, it would be great if you could obtain the Flux query you ran, as well as the response body that it returned. I'll keep an eye out for this crash in the meantime.

**Comment by docmerlin** [comment]
Will do.

**Comment by russorat** [comment]
we can reopen if we see this again
