### ISSUE TITLE
 Chronograf (1.7.4) o is not a function

### ISSUE THREAD

**Issue by crysaro** [influxdata/chronograf#4907]
What browser are you using (name and version)?
chrome Version 71.0.3578.98
What operating system are you using?
Windows 10
Please describe what you were trying to do when you encountered this error:
I was typing the Kapacitor name then wizard suddenly proceded to next and then displayed the error.
```
TypeError: o is not a function
    at d.<anonymous> (http://localhost:8888/src.96776a90.js:4691:3998)
    at pl (http://localhost:8888/src.96776a90.js:716:45572)
    at dl (http://localhost:8888/src.96776a90.js:716:45322)
    at xi (http://localhost:8888/src.96776a90.js:716:84392)
    at wi (http://localhost:8888/src.96776a90.js:716:79945)
    at ki (http://localhost:8888/src.96776a90.js:716:79561)
    at Le (http://localhost:8888/src.96776a90.js:716:90853)
    at We (http://localhost:8888/src.96776a90.js:716:10444)
    at Fn (http://localhost:8888/src.96776a90.js:716:30800)
    at Si (http://localhost:8888/src.96776a90.js:716:85578)
```

**Comment by russorat** [comment]
fixed in https://github.com/influxdata/chronograf/issues/5080
