### ISSUE TITLE
 Chronograf (1.7.3) Invalid size returned for cell 3 of value NaN

### ISSUE THREAD

**Issue by abhinayak95** [influxdata/chronograf#4914]
```Error: Invalid size returned for cell 3 of value NaN
    at i.value (http://localhost:8888/src.85d3bd0b.js:2821:1411)
    at i.value (http://localhost:8888/src.85d3bd0b.js:2821:2700)
    at r.value (http://localhost:8888/src.85d3bd0b.js:2825:2359)
    at f.value (http://localhost:8888/src.85d3bd0b.js:2896:12908)
    at f.value (http://localhost:8888/src.85d3bd0b.js:2896:11170)
    at ia (http://localhost:8888/src.85d3bd0b.js:716:58760)
    at aa (http://localhost:8888/src.85d3bd0b.js:716:58602)
    at fa (http://localhost:8888/src.85d3bd0b.js:716:60859)
    at Wa (http://localhost:8888/src.85d3bd0b.js:716:74893)
    at Va (http://localhost:8888/src.85d3bd0b.js:716:75239)```

**Comment by russorat** [comment]
@abhinayak95 please upgrade to the latest chronograf 1.7.5.
