### ISSUE TITLE
 Chronograf (1.7.6) o is not a function

### ISSUE THREAD

**Issue by Derr22** [influxdata/chronograf#5042]
What browser are you using (name and version)?
Chrome 71.0.3578.98

What operating system are you using?
Windows 10 64x

Please describe what you were trying to do when you encountered this error:
I tryed to connect influxDB
It was first using of Chronograf
```
TypeError: o is not a function
    at d.<anonymous> (http://localhost:8888/src.5a8fa5bd.js:4691:3998)
    at pl (http://localhost:8888/src.5a8fa5bd.js:716:45572)
    at dl (http://localhost:8888/src.5a8fa5bd.js:716:45322)
    at xi (http://localhost:8888/src.5a8fa5bd.js:716:84392)
    at wi (http://localhost:8888/src.5a8fa5bd.js:716:79945)
    at ki (http://localhost:8888/src.5a8fa5bd.js:716:79561)
    at Le (http://localhost:8888/src.5a8fa5bd.js:716:90853)
    at We (http://localhost:8888/src.5a8fa5bd.js:716:10444)
    at Fn (http://localhost:8888/src.5a8fa5bd.js:716:30800)
    at Si (http://localhost:8888/src.5a8fa5bd.js:716:85578)
```

**Comment by russorat** [comment]
Closing due to lack of response.
