### ISSUE TITLE
 Chronograf (1.7.6) o is not a function

### ISSUE THREAD

**Issue by nasked** [influxdata/chronograf#5051]
What browser are you using (name and version)?

What operating system are you using?

Please describe what you were trying to do when you encountered this error:

```
TypeError: o is not a function
    at d.<anonymous> (http://10.17.17.24:8888/src.5a8fa5bd.js:4691:3998)
    at pl (http://10.17.17.24:8888/src.5a8fa5bd.js:716:45572)
    at dl (http://10.17.17.24:8888/src.5a8fa5bd.js:716:45322)
    at xi (http://10.17.17.24:8888/src.5a8fa5bd.js:716:84392)
    at wi (http://10.17.17.24:8888/src.5a8fa5bd.js:716:79945)
    at ki (http://10.17.17.24:8888/src.5a8fa5bd.js:716:79561)
    at Le (http://10.17.17.24:8888/src.5a8fa5bd.js:716:90853)
    at We (http://10.17.17.24:8888/src.5a8fa5bd.js:716:10444)
    at Fn (http://10.17.17.24:8888/src.5a8fa5bd.js:716:30800)
    at Si (http://10.17.17.24:8888/src.5a8fa5bd.js:716:85578)
```

**Comment by russorat** [comment]
@nasked could you provide the additional information requested to help us troubleshoot?

**Comment by russorat** [comment]
closing for now. please reopen with additional information if you see this again.
