### ISSUE TITLE
 Chronograf (1.7.7) o is not a function

### ISSUE THREAD

**Issue by bdmunday** [influxdata/chronograf#5055]
What browser are you using (name and version)? Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)

What operating system are you using? Windows 10 Pro

Please describe what you were trying to do when you encountered this error:
I had already setup Chronograf the day before and was attempting to launch it. I was having to re-initialize Chronograf, so I was plugging in the settings. The InfluxDB screen was fine. The dashboards showed only "System" as an option not the other 20-25 options it normally shows. The Kapacitor screen came up looking normal. I wanted the connection name to not be "New Kapacitor" and that is when when Chronograf went to it's error screen.

I was able to reproduce this repeatedly. I copied my setting to a sticky note on my PC so that I could copy-paste settings into the various screens. It's all kind of weird.

TICK Stack setup:
The stack is not completely setup. Telegraf hasn't been put into the stack yet. The entire stack is running on the latest version of Docker. Each component is running in it's own container, and they are all tied to the same docker network. The combined stack is also running Elasticsearch 6.5.4, Logstash 6.5.4, and Kibana 6.5.4. I am building a combined logs and metrics stack. The remaining containers to bring up are Telegraf and Grafana.

```
TypeError: o is not a function
    at d.<anonymous> (http://10.50.1.136:8888/src.216c1ae9.js:4691:3998)
    at pl (http://10.50.1.136:8888/src.216c1ae9.js:716:45572)
    at dl (http://10.50.1.136:8888/src.216c1ae9.js:716:45322)
    at xi (http://10.50.1.136:8888/src.216c1ae9.js:716:84392)
    at wi (http://10.50.1.136:8888/src.216c1ae9.js:716:79945)
    at ki (http://10.50.1.136:8888/src.216c1ae9.js:716:79561)
    at Le (http://10.50.1.136:8888/src.216c1ae9.js:716:90853)
    at We (http://10.50.1.136:8888/src.216c1ae9.js:716:10444)
    at Fn (http://10.50.1.136:8888/src.216c1ae9.js:716:30800)
    at Si (http://10.50.1.136:8888/src.216c1ae9.js:716:85578)
```

**Comment by russorat** [comment]
fixed in https://github.com/influxdata/chronograf/issues/5080
