### ISSUE TITLE
 Chronograf (1.7.7) Cannot read property 'ast' of undefined

### ISSUE THREAD

**Issue by langero** [influxdata/chronograf#5056]
What browser are you using (name and version)?

What operating system are you using?

Please describe what you were trying to do when you encountered this error:

```
TypeError: Cannot read property 'ast' of undefined
    at v (http://localhost:8888/src.216c1ae9.js:3731:3001)
    at a.configureFinalMapState (http://localhost:8888/src.216c1ae9.js:801:2471)
    at a.computeStateProps (http://localhost:8888/src.216c1ae9.js:801:2263)
    at a.updateStatePropsIfNeeded (http://localhost:8888/src.216c1ae9.js:801:3221)
    at a.render (http://localhost:8888/src.216c1ae9.js:801:5741)
    at ia (http://localhost:8888/src.216c1ae9.js:716:58760)
    at aa (http://localhost:8888/src.216c1ae9.js:716:58602)
    at fa (http://localhost:8888/src.216c1ae9.js:716:60859)
    at Wa (http://localhost:8888/src.216c1ae9.js:716:74893)
    at Va (http://localhost:8888/src.216c1ae9.js:716:75239)
```

**Comment by russorat** [comment]
@langero could you provide the additional information requested to help us troubleshoot?

**Comment by langero** [comment]
Hi - the problem no longer exists after a reinstallation. I think it was a configuration error.
