### ISSUE TITLE
 Chronograf (1.7.7) o is not a function

### ISSUE THREAD

**Issue by anoper** [influxdata/chronograf#5057]
What browser are you using (name and version)?

What operating system are you using?

Please describe what you were trying to do when you encountered this error:

```
TypeError: o is not a function
    at d.<anonymous> (http://192.168.1.85:8888/src.216c1ae9.js:4691:3998)
    at pl (http://192.168.1.85:8888/src.216c1ae9.js:716:45572)
    at dl (http://192.168.1.85:8888/src.216c1ae9.js:716:45322)
    at xi (http://192.168.1.85:8888/src.216c1ae9.js:716:84392)
    at wi (http://192.168.1.85:8888/src.216c1ae9.js:716:79945)
    at ki (http://192.168.1.85:8888/src.216c1ae9.js:716:79561)
    at Le (http://192.168.1.85:8888/src.216c1ae9.js:716:90853)
    at We (http://192.168.1.85:8888/src.216c1ae9.js:716:10444)
    at Fn (http://192.168.1.85:8888/src.216c1ae9.js:716:30800)
    at Si (http://192.168.1.85:8888/src.216c1ae9.js:716:85578)
```

**Comment by russorat** [comment]
@anoper could you provide the additional information requested to help us troubleshoot?

**Comment by russorat** [comment]
closing for now. please reopen with additional information.
