### ISSUE TITLE
 Chronograf (1.7.7) toFixed() digits argument must be between 0 and 100

### ISSUE THREAD

**Issue by HPParasite** [influxdata/chronograf#5058]
What browser are you using (name and version)?

What operating system are you using?

Please describe what you were trying to do when you encountered this error:

```
RangeError: toFixed() digits argument must be between 0 and 100
    at Number.toFixed (<anonymous>)
    at d.get (http://192.168.98.174:8888/src.216c1ae9.js:3216:5009)
    at d.get (http://192.168.98.174:8888/src.216c1ae9.js:3216:4580)
    at d.get (http://192.168.98.174:8888/src.216c1ae9.js:3216:6017)
    at d.value (http://192.168.98.174:8888/src.216c1ae9.js:3216:3404)
    at d.value (http://192.168.98.174:8888/src.216c1ae9.js:1860:2204)
    at ia (http://192.168.98.174:8888/src.216c1ae9.js:716:58760)
    at aa (http://192.168.98.174:8888/src.216c1ae9.js:716:58602)
    at fa (http://192.168.98.174:8888/src.216c1ae9.js:716:60859)
    at Wa (http://192.168.98.174:8888/src.216c1ae9.js:716:74893)
```

**Comment by russorat** [comment]
@HPParasite could you provide the additional information requested to help us troubleshoot?

**Comment by russorat** [comment]
seems like we should verify the range of the value used in toFixed when we use it.
https://github.com/influxdata/chronograf/search?q=%22toFixed%22&unscoped_q=%22toFixed%22&type=Code
