### ISSUE TITLE
 Chronograf (1.7.6) o is not a function

### ISSUE THREAD

**Issue by mxmingya** [influxdata/chronograf#5067]
What browser are you using (name and version)?
Chrome
What operating system are you using?
MacOS
Please describe what you were trying to do when you encountered this error:
setting up chronograf connection to telegraf and influxdb. 
```
TypeError: o is not a function
    at d.<anonymous> (http://127.0.0.1:8888/src.cb07884c.js:4691:3998)
    at pl (http://127.0.0.1:8888/src.cb07884c.js:716:45572)
    at dl (http://127.0.0.1:8888/src.cb07884c.js:716:45322)
    at xi (http://127.0.0.1:8888/src.cb07884c.js:716:84392)
    at wi (http://127.0.0.1:8888/src.cb07884c.js:716:79945)
    at ki (http://127.0.0.1:8888/src.cb07884c.js:716:79561)
    at Le (http://127.0.0.1:8888/src.cb07884c.js:716:90853)
    at We (http://127.0.0.1:8888/src.cb07884c.js:716:10444)
    at Fn (http://127.0.0.1:8888/src.cb07884c.js:716:30800)
    at Si (http://127.0.0.1:8888/src.cb07884c.js:716:85578)
```

**Comment by russorat** [comment]
fixed in https://github.com/influxdata/chronograf/issues/5080
