### ISSUE TITLE
 Chronograf (1.7.7) o is not a function

### ISSUE THREAD

**Issue by Yify-93** [influxdata/chronograf#5075]
What browser are you using (name and version)?

What operating system are you using?

Please describe what you were trying to do when you encountered this error:

```
TypeError: o is not a function
    at d.<anonymous> (http://localhost:8888/src.216c1ae9.js:4691:3998)
    at pl (http://localhost:8888/src.216c1ae9.js:716:45572)
    at dl (http://localhost:8888/src.216c1ae9.js:716:45322)
    at xi (http://localhost:8888/src.216c1ae9.js:716:84392)
    at wi (http://localhost:8888/src.216c1ae9.js:716:79945)
    at ki (http://localhost:8888/src.216c1ae9.js:716:79561)
    at Le (http://localhost:8888/src.216c1ae9.js:716:90853)
    at We (http://localhost:8888/src.216c1ae9.js:716:10444)
    at Fn (http://localhost:8888/src.216c1ae9.js:716:30800)
    at Si (http://localhost:8888/src.216c1ae9.js:716:85578)
```

**Comment by russorat** [comment]
fixed in https://github.com/influxdata/chronograf/issues/5080
