### ISSUE TITLE
 Chronograf (1.7.8) Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by clancye** [influxdata/chronograf#5094]
**What browser are you using (name and version)?**
Chrome, 71.0.3578.98 (Official Build) (64-bit) (cohort: Stable)

**What operating system are you using?**
Ubuntu 18.04 is running Influx and Chronograf. I was accessing Chronograf on a Windows 10 64-bit machine.

**Please describe what you were trying to do when you encountered this error:**

1. I went to https://docs.influxdata.com/flux/v0.12/functions/transformations/drop/ and copied the following flux query into the Data Explorer in Chronograf:

`from(bucket: "telegraf/autogen")
  |> range(start: -5m)
  |> drop(fn: (column) => column =~ /usage*/)`

2. I changed '/usage*/' to '/*/'
3. Chronograf crashes and I have to restart the service.

```
TypeError: Cannot read property 'split' of undefined
    at d.get (http://influx.precision-combustion.com:8888/src.d79557ef.js:3800:4592)
    at d.value (http://influx.precision-combustion.com:8888/src.d79557ef.js:3800:3999)
    at d.value (http://influx.precision-combustion.com:8888/src.d79557ef.js:3800:3141)
    at xi (http://influx.precision-combustion.com:8888/src.d79557ef.js:716:84251)
    at wi (http://influx.precision-combustion.com:8888/src.d79557ef.js:716:79945)
    at ki (http://influx.precision-combustion.com:8888/src.d79557ef.js:716:79561)
    at Ha (http://influx.precision-combustion.com:8888/src.d79557ef.js:716:78073)
    at Object.enqueueSetState (http://influx.precision-combustion.com:8888/src.d79557ef.js:716:47062)
    at g.h.setState (http://influx.precision-combustion.com:8888/src.d79557ef.js:708:1621)
    at g.<anonymous> (http://influx.precision-combustion.com:8888/src.d79557ef.js:3844:3438)
```

**Comment by 121watts** [comment]
@clancye thanks for writing in! When I run that query locally, I don't get a javascript runtime error but my flux instance does panic.  In talks with the flux team now.
