### ISSUE TITLE
 Chronograf (1.7.7) o is not a function

### ISSUE THREAD

**Issue by jairotunior** [influxdata/chronograf#5121]
What browser are you using Google Chrome Versión 72.0.3626.121 (Build oficial) (64 bits)?

What operating system are you using?

Please describe what you were trying to do when you encountered this error:

```
TypeError: o is not a function
    at d.<anonymous> (http://206.189.180.96/src.216c1ae9.js:4691:3998)
    at pl (http://206.189.180.96/src.216c1ae9.js:716:45572)
    at dl (http://206.189.180.96/src.216c1ae9.js:716:45322)
    at xi (http://206.189.180.96/src.216c1ae9.js:716:84392)
    at wi (http://206.189.180.96/src.216c1ae9.js:716:79945)
    at ki (http://206.189.180.96/src.216c1ae9.js:716:79561)
    at Le (http://206.189.180.96/src.216c1ae9.js:716:90853)
    at We (http://206.189.180.96/src.216c1ae9.js:716:10444)
    at Fn (http://206.189.180.96/src.216c1ae9.js:716:30800)
    at Si (http://206.189.180.96/src.216c1ae9.js:716:85578)
```

**Comment by russorat** [comment]
i believe this was fixed in chronograf 1.7.8
