### ISSUE TITLE
 Chronograf (1.7.11) Invalid size returned for cell 5 of value NaN

### ISSUE THREAD

**Issue by vstepanov-lohika-tix** [influxdata/chronograf#5180]
What browser are you using (name and version)?
Chrome Version 74.0.3729.131
What operating system are you using?
Windows 10x64

Please describe what you were trying to do when you encountered this error:
1) Create a new simple query
2) Run it successfully
3) Add new query tab
4) Copy and run the same query

```
Error: Invalid size returned for cell 5 of value NaN
    at i.value (http://localhost:8888/src.f4eab669.js:2833:1411)
    at i.value (http://localhost:8888/src.f4eab669.js:2833:2700)
    at r.value (http://localhost:8888/src.f4eab669.js:2837:2359)
    at f.value (http://localhost:8888/src.f4eab669.js:2908:12908)
    at f.value (http://localhost:8888/src.f4eab669.js:2908:11170)
    at ia (http://localhost:8888/src.f4eab669.js:716:58760)
    at aa (http://localhost:8888/src.f4eab669.js:716:58602)
    at fa (http://localhost:8888/src.f4eab669.js:716:60859)
    at Wa (http://localhost:8888/src.f4eab669.js:716:74893)
    at Va (http://localhost:8888/src.f4eab669.js:716:75239)
```

**Comment by timhallinflux** [comment]
I cannot reproduce on 1.7.11.  Can you provide a bit more information?
Or attempt to reproduce with 1.7.12?

**Comment by russorat** [comment]
closing due to lack of response.
