### ISSUE TITLE
 Chronograf (1.7.11) Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by morese** [influxdata/chronograf#5182]
What browser are you using (name and version)?

What operating system are you using?

Please describe what you were trying to do when you encountered this error:

```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at wa (http://192.168.0.98:8888/src.f4eab669.js:716:66018)
    at xi (http://192.168.0.98:8888/src.f4eab669.js:716:82700)
    at wi (http://192.168.0.98:8888/src.f4eab669.js:716:79945)
    at ki (http://192.168.0.98:8888/src.f4eab669.js:716:79561)
    at Si (http://192.168.0.98:8888/src.f4eab669.js:716:85610)
    at Rn (http://192.168.0.98:8888/src.f4eab669.js:716:30543)
```

**Comment by russorat** [comment]
@morese could you answer the following questions?

What browser are you using (name and version)?

What operating system are you using?

Please describe what you were trying to do when you encountered this error:
