### ISSUE TITLE
 Chronograf (1.7.11) Invalid size returned for cell 2 of value NaN

### ISSUE THREAD

**Issue by wduarte70** [influxdata/chronograf#5209]
What browser are you using (name and version)? Chrome Version 75.0.3770.100 (Official Build) (64-bit)

What operating system are you using? MacOs Mojave 10.14.5

Please describe what you were trying to do when you encountered this error:

Just using your exercise "

Version 75.0.3770.100 (Official Build) (64-bit)
"

```
Error: Invalid size returned for cell 2 of value NaN
    at i.value (https://mcfly-19096071.influxcloud.net/src.f4eab669.js:2833:1411)
    at i.value (https://mcfly-19096071.influxcloud.net/src.f4eab669.js:2833:2700)
    at r.value (https://mcfly-19096071.influxcloud.net/src.f4eab669.js:2837:2359)
    at f.value (https://mcfly-19096071.influxcloud.net/src.f4eab669.js:2908:12908)
    at f.value (https://mcfly-19096071.influxcloud.net/src.f4eab669.js:2908:11170)
    at ia (https://mcfly-19096071.influxcloud.net/src.f4eab669.js:716:58760)
    at aa (https://mcfly-19096071.influxcloud.net/src.f4eab669.js:716:58602)
    at fa (https://mcfly-19096071.influxcloud.net/src.f4eab669.js:716:60859)
    at Wa (https://mcfly-19096071.influxcloud.net/src.f4eab669.js:716:74893)
    at Va (https://mcfly-19096071.influxcloud.net/src.f4eab669.js:716:75239)
```

**Comment by timhallinflux** [comment]
Thanks @wduarte70 -- I can see you are using our free trial in InfluxCloud.  Can you let me know which query in the getting started exercise you were running? We can then dig into that a bit further.  NaN stands for "not a number"  -- so, I'm not sure why that might appear as a part of the tutorial.

**Comment by russorat** [comment]
closing due to lack of response.
