### ISSUE TITLE
 Chronograf (1.7.13) Cannot read property 'split' of null

### ISSUE THREAD

**Issue by zenbiking** [influxdata/chronograf#5263]
What browser are you using (name and version)?
Chrome Version 76.0.3809.100 (Official Build) (64-bit)

What operating system are you using?

OS X 10.14.6

Please describe what you were trying to do when you encountered this error:

Opened up influxdb, connected to chronograph, and then clicked on the Explore menu item on the LH side of the screen.

```
TypeError: Cannot read property 'split' of null
    at https://hoverboard-cd873146.influxcloud.net/src.b085f594.js:3396:2294
    at Array.filter (<anonymous>)
    at Object.s.reset [as onResetTimeMachine] (https://hoverboard-cd873146.influxcloud.net/src.b085f594.js:3396:2217)
    at d.c (https://hoverboard-cd873146.influxcloud.net/src.b085f594.js:4118:3369)
    at new d (https://hoverboard-cd873146.influxcloud.net/src.b085f594.js:1911:1841)
    at Tl (https://hoverboard-cd873146.influxcloud.net/src.b085f594.js:717:48187)
    at ja (https://hoverboard-cd873146.influxcloud.net/src.b085f594.js:717:63002)
    at $a (https://hoverboard-cd873146.influxcloud.net/src.b085f594.js:717:69008)
    at oo (https://hoverboard-cd873146.influxcloud.net/src.b085f594.js:717:91055)
    at uo (https://hoverboard-cd873146.influxcloud.net/src.b085f594.js:717:91442)
```

**Comment by timhallinflux** [comment]
Issue occurred when attempting to access the data explorer.  It appears intermittently.  But, once it occurs, you lose access to the data explorer entirely.  Cannot hard refresh the page to recover.

**Comment by zenbiking** [comment]
> Issue occurred when attempting to access the data explorer. It appears intermittently. But, once it occurs, you lose access to the data explorer entirely. Cannot hard refresh the page to recover.

I did a little more testing this AM. Once this occurs, opening an incognito session allows access to the data explorer. After this, I went back and cleared my cache and cookies out of Chrome, and that also allowed me to access the data explorer again.
