### ISSUE TITLE
 Chronograf (1.7.13) Cannot read property 'split' of null

### ISSUE THREAD

**Issue by venkyrprabhu** [influxdata/chronograf#5275]
What browser are you using (name and version)? 
Google Chrome - Version 75.0.3770.100 (Official Build) (64-bit) 

What operating system are you using?
Mac OS Mojave - 10.14.6  
Please describe what you were trying to do when you encountered this error:
Error when launching DataExplorer (http://locahost:8888/sources/1/chronograf/data-explorer) after connecting an InfluxDB datasource

```
TypeError: Cannot read property 'split' of null
    at http://localhost:8888/src.7d0d0859.js:3396:2294
    at Array.filter (<anonymous>)
    at Object.s.reset [as onResetTimeMachine] (http://localhost:8888/src.7d0d0859.js:3396:2217)
    at d.c (http://localhost:8888/src.7d0d0859.js:4118:3369)
    at new d (http://localhost:8888/src.7d0d0859.js:1911:1841)
    at Tl (http://localhost:8888/src.7d0d0859.js:717:48187)
    at ja (http://localhost:8888/src.7d0d0859.js:717:63002)
    at $a (http://localhost:8888/src.7d0d0859.js:717:69008)
    at oo (http://localhost:8888/src.7d0d0859.js:717:91055)
    at uo (http://localhost:8888/src.7d0d0859.js:717:91442)
```

**Comment by venkyrprabhu** [comment]
Just verified that the Data Explorer view works fine on Safari (Version 12.1.2 (14607.3.9) , but still fails to load on Chrome .

**Comment by cgwyllie** [comment]
This looks like a duplicate of these issues: https://github.com/influxdata/chronograf/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+split+of+null

According to https://github.com/influxdata/chronograf/issues/5271 it should be resolved in 1.7.14.
