### ISSUE TITLE
 Chronograf (1.7.12) Invalid size returned for cell 1 of value NaN

### ISSUE THREAD

**Issue by 9seed** [influxdata/chronograf#5299]
What browser are you using (name and version)?
Chrome Version 79.0.3941.4 (Official Build) dev (64-bit)

What operating system are you using?
macOS High Sierra Version 10.13.5

Please describe what you were trying to do when you encountered this error:

```
Error: Invalid size returned for cell 1 of value NaN
    at i.value (http://localhost:8888/src.28073177.js:2833:1411)
    at i.value (http://localhost:8888/src.28073177.js:2833:2700)
    at r.value (http://localhost:8888/src.28073177.js:2837:2359)
    at f.value (http://localhost:8888/src.28073177.js:2908:12908)
    at f.value (http://localhost:8888/src.28073177.js:2908:11170)
    at ia (http://localhost:8888/src.28073177.js:716:58760)
    at aa (http://localhost:8888/src.28073177.js:716:58602)
    at fa (http://localhost:8888/src.28073177.js:716:60859)
    at Wa (http://localhost:8888/src.28073177.js:716:74893)
    at Va (http://localhost:8888/src.28073177.js:716:75239)
```

**Comment by glinton** [comment]
@9seed  can you identify clear steps to reproduce this, thanks.

**Comment by glinton** [comment]
closing in favor of #5347 please comment there with any additional info
