### ISSUE TITLE
 Chronograf (1.7.14) Requested index 0 is outside of range 0..-Infinity

### ISSUE THREAD

**Issue by Eson-Jia** [influxdata/chronograf#5319]
What browser are you using (name and version)?
版本 78.0.3904.97（正式版本） （64 位）
What operating system are you using?
win10
Please describe what you were trying to do when you encountered this error:

```
Error: Requested index 0 is outside of range 0..-Infinity
    at i.value (http://192.168.1.74:8888/src.d4e31fda.js:2848:1133)
    at i.value (http://192.168.1.74:8888/src.d4e31fda.js:2848:2947)
    at i.value (http://192.168.1.74:8888/src.d4e31fda.js:2848:3477)
    at i.value (http://192.168.1.74:8888/src.d4e31fda.js:2848:2577)
    at r.value (http://192.168.1.74:8888/src.d4e31fda.js:2852:2359)
    at f.value (http://192.168.1.74:8888/src.d4e31fda.js:2923:12908)
    at f.value (http://192.168.1.74:8888/src.d4e31fda.js:2923:11170)
    at Ba (http://192.168.1.74:8888/src.d4e31fda.js:717:65834)
    at ja (http://192.168.1.74:8888/src.d4e31fda.js:717:65629)
    at $a (http://192.168.1.74:8888/src.d4e31fda.js:717:69008)
```

**Comment by russorat** [comment]
Thanks for opening an issue. Could you please describe what you were doing when you encountered this error?

**Comment by sranka** [comment]
This issue does not appear anymore in the newest 1.9 chronograf.
