### ISSUE TITLE
 Chronograf (1.7.14) Maximum call stack size exceeded

### ISSUE THREAD

**Issue by sbarale** [influxdata/chronograf#5321]
What browser are you using (name and version)?

What operating system are you using?

Please describe what you were trying to do when you encountered this error:

```
RangeError: Maximum call stack size exceeded
    at p (http://app.dashfloow.com:8888/src.d4e31fda.js:3289:2561)
    at http://app.dashfloow.com:8888/src.d4e31fda.js:3122:365
    at s.value (http://app.dashfloow.com:8888/src.d4e31fda.js:3307:1696)
    at Ba (http://app.dashfloow.com:8888/src.d4e31fda.js:717:65834)
    at ja (http://app.dashfloow.com:8888/src.d4e31fda.js:717:65629)
    at $a (http://app.dashfloow.com:8888/src.d4e31fda.js:717:69008)
    at oo (http://app.dashfloow.com:8888/src.d4e31fda.js:717:91055)
    at uo (http://app.dashfloow.com:8888/src.d4e31fda.js:717:91442)
    at Yo (http://app.dashfloow.com:8888/src.d4e31fda.js:717:98524)
    at $o (http://app.dashfloow.com:8888/src.d4e31fda.js:717:97904)
```

**Comment by russorat** [comment]
@sbarale thanks for reporting. could you fill in the details to the following questions?
What browser are you using (name and version)?
What operating system are you using?
Please describe what you were trying to do when you encountered this error?

**Comment by sbarale** [comment]
@russorat sorry, just saw this :(.

I was using Chrome, on Mac. The system is running on Ubuntu 
Linux ip-172-30-1-78 4.15.0-1051-aws #53-Ubuntu SMP Wed Sep 18 13:35:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
root@ip-172-30-1-78:~#

Honestly I can't remember what I was doing. I will let you know if it comes back.

**Comment by russorat** [comment]
@sbarale thanks! I'd recommend updating to 1.8 if possible. I'll close this since it isn't actionable for us. If it happens again, let us know what you were doing and we will investigate.
