### ISSUE TITLE
 Chronograf (1.8.0) Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by marcioaneves** [influxdata/chronograf#5440]
What browser are you using (name and version)? Chrome 

What operating system are you using? Windows 10

Please describe what you were trying to do when you encountered this error:

```
TypeError: Cannot read property 'name' of undefined
    at http://nevesrasp:8888/src.5692061f.js:2365:385
    at Array.map (<anonymous>)
    at l (http://nevesrasp:8888/src.5692061f.js:2365:310)
    at sa (http://nevesrasp:8888/src.5692061f.js:717:55869)
    at $a (http://nevesrasp:8888/src.5692061f.js:717:68127)
    at oo (http://nevesrasp:8888/src.5692061f.js:717:91055)
    at uo (http://nevesrasp:8888/src.5692061f.js:717:91442)
    at Yo (http://nevesrasp:8888/src.5692061f.js:717:98524)
    at $o (http://nevesrasp:8888/src.5692061f.js:717:97904)
    at jo (http://nevesrasp:8888/src.5692061f.js:717:96925)
```

**Comment by russorat** [comment]
@marcioaneves thanks for the issue. can you please describe what you were trying to do when you encountered this error?

**Comment by sranka** [comment]
duplicate of #5720
