### ISSUE TITLE
 Chronograf (1.7.14) 未指明的错误。

### ISSUE THREAD

**Issue by ljtxdy123** [influxdata/chronograf#5452]
What browser are you using (name and version)?

What operating system are you using?

Please describe what you were trying to do when you encountered this error:

```
Error: 未指明的错误。
   at yr (http://39.107.141.202:8888/src.d4e31fda.js:717:38874)
   at io (http://39.107.141.202:8888/src.d4e31fda.js:717:88783)
   at oo (http://39.107.141.202:8888/src.d4e31fda.js:717:91076)
   at uo (http://39.107.141.202:8888/src.d4e31fda.js:717:91439)
   at Yo (http://39.107.141.202:8888/src.d4e31fda.js:717:98524)
   at $o (http://39.107.141.202:8888/src.d4e31fda.js:717:97904)
   at jo (http://39.107.141.202:8888/src.d4e31fda.js:717:96925)
   at ho (http://39.107.141.202:8888/src.d4e31fda.js:717:95738)
   at kl.enqueueSetState (http://39.107.141.202:8888/src.d4e31fda.js:717:47534)
   at _.prototype.setState (http://39.107.141.202:8888/src.d4e31fda.js:708:1683)
```

**Comment by russorat** [comment]
@ljtxdy123 thanks! could you please add the following details?

What browser are you using (name and version)?

What operating system are you using?

Please describe what you were trying to do when you encountered this error?

**Comment by timhallinflux** [comment]
any additional info @ljtxdy123 ?  Otherwise, we'll simply close this issue.  Thanks.
