### ISSUE TITLE
 Chronograf (1.7.17) Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by AlexHeylin** [influxdata/chronograf#5468]
What browser are you using (name and version)?
Chrome Version 81.0.4044.122 (Official Build) (64-bit)

What operating system are you using?
Windows 10 Pro 1909 (Build 18363.778)

Please describe what you were trying to do when you encountered this error:
Cronograf main page (/sources/1/status) reported this error in News Feed and asked me to report it. 
![cronograf error](https://user-images.githubusercontent.com/270973/80650542-17e1da80-8a6c-11ea-853d-ff340e806912.PNG)

```
TypeError: Cannot read property 'name' of undefined
    at http://192.168.12.78:8888/src.f9bc0d55.js:2363:385
    at Array.map (<anonymous>)
    at l (http://192.168.12.78:8888/src.f9bc0d55.js:2363:310)
    at sa (http://192.168.12.78:8888/src.f9bc0d55.js:717:55869)
    at $a (http://192.168.12.78:8888/src.f9bc0d55.js:717:68127)
    at oo (http://192.168.12.78:8888/src.f9bc0d55.js:717:91055)
    at uo (http://192.168.12.78:8888/src.f9bc0d55.js:717:91442)
    at Yo (http://192.168.12.78:8888/src.f9bc0d55.js:717:98524)
    at $o (http://192.168.12.78:8888/src.f9bc0d55.js:717:97904)
    at eu (http://192.168.12.78:8888/src.f9bc0d55.js:717:99279)
```

**Comment by russorat** [comment]
@AlexHeylin thank you for the issue. this is fixed in the latest chronograf release.
