### ISSUE TITLE
 Chronograf (1.7.17) Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by rsolimeno** [influxdata/chronograf#5495]
What browser are you using (name and version)? Chromium Version 83.0.4103.61 (Official Build) snap (64-bit)

What operating system are you using?  Raspbian GNU/Linux 10 (buster)

Please describe what you were trying to do when you encountered this error: Opened "Status" page by clicking on polygon icon top left menu,
```
TypeError: Cannot read property 'name' of undefined
    at http://idiot:8888/src.f9bc0d55.js:2363:385
    at Array.map (<anonymous>)
    at l (http://idiot:8888/src.f9bc0d55.js:2363:310)
    at sa (http://idiot:8888/src.f9bc0d55.js:717:55869)
    at $a (http://idiot:8888/src.f9bc0d55.js:717:68127)
    at oo (http://idiot:8888/src.f9bc0d55.js:717:91055)
    at uo (http://idiot:8888/src.f9bc0d55.js:717:91442)
    at Yo (http://idiot:8888/src.f9bc0d55.js:717:98524)
    at $o (http://idiot:8888/src.f9bc0d55.js:717:97904)
    at eu (http://idiot:8888/src.f9bc0d55.js:717:99279)
    at Mn (http://idiot:8888/src.f9bc0d55.js:717:30665)
```

**Comment by glinton** [comment]
Closed by https://github.com/influxdata/chronograf/pull/5420, please upgrade to the 1.8.x line or [nightly builds](https://portal.influxdata.com/downloads/).
