### ISSUE TITLE
 Chronograf (1.7.16) Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by HeidiRechek** [influxdata/chronograf#5497]
What browser are you using (name and version)?
chrome
What operating system are you using?
ubuntu
Please describe what you were trying to do when you encountered this error:
attempting to view news feed on home page
```
TypeError: Cannot read property 'name' of undefined
    at http://1*.*.*.*:8888/src.a5ab7481.js:2363:385
    at Array.map (<anonymous>)
    at l (http://1*.*.*.*:8888/src.a5ab7481.js:2363:310)
    at sa (http://1*.*.*.*:8888/src.a5ab7481.js:717:55869)
    at $a (http://1*.*.*.*:8888/src.a5ab7481.js:717:68127)
    at oo (http://1*.*.*.*:8888/src.a5ab7481.js:717:91055)
    at uo (http://1*.*.*.*:8888/src.a5ab7481.js:717:91442)
    at Yo (http://1*.*.*.*:8888/src.a5ab7481.js:717:98524)
    at $o (http://1*.*.*.*:8888/src.a5ab7481.js:717:97904)
    at eu (http://1*.*.*.*:8888/src.a5ab7481.js:717:99279)
```

**Comment by glinton** [comment]
Closed by https://github.com/influxdata/chronograf/pull/5420, please upgrade to the 1.8.x line or [nightly builds](https://portal.influxdata.com/downloads/).
