### ISSUE TITLE
 Chronograf (1.7.11) Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by tymac753** [influxdata/chronograf#5509]
What browser are you using (name and version)?

Edge Version 83.0.478.45 (

What operating system are you using?

Windows 10

Please describe what you were trying to do when you encountered this error:

Trying to view the news feed on landing page

```
TypeError: Cannot read property 'name' of undefined
    at http://10.1.110.52:8888/src.f4eab669.js:2350:385
    at Array.map (<anonymous>)
    at l (http://10.1.110.52:8888/src.f4eab669.js:2350:310)
    at ca (http://10.1.110.52:8888/src.f4eab669.js:716:59548)
    at fa (http://10.1.110.52:8888/src.f4eab669.js:716:60685)
    at Wa (http://10.1.110.52:8888/src.f4eab669.js:716:74893)
    at Va (http://10.1.110.52:8888/src.f4eab669.js:716:75239)
    at wi (http://10.1.110.52:8888/src.f4eab669.js:716:79907)
    at ki (http://10.1.110.52:8888/src.f4eab669.js:716:79561)
    at Ha (http://10.1.110.52:8888/src.f4eab669.js:716:78073)
```

**Comment by russorat** [comment]
@tymac753 this has been fixed in the latest release. please upgrade.
