### ISSUE TITLE
 Chronograf (1.7.14) 未指明的错误。

### ISSUE THREAD

**Issue by wuststudent** [influxdata/chronograf#5537]
What browser are you using (name and version)?

What operating system are you using?

Please describe what you were trying to do when you encountered this error:

```
Error: 未指明的错误。
   at yr (http://183.221.28.171:4010/src.d4e31fda.js:717:38874)
   at io (http://183.221.28.171:4010/src.d4e31fda.js:717:88783)
   at oo (http://183.221.28.171:4010/src.d4e31fda.js:717:91076)
   at uo (http://183.221.28.171:4010/src.d4e31fda.js:717:91439)
   at Yo (http://183.221.28.171:4010/src.d4e31fda.js:717:98524)
   at $o (http://183.221.28.171:4010/src.d4e31fda.js:717:97904)
   at jo (http://183.221.28.171:4010/src.d4e31fda.js:717:96925)
   at ho (http://183.221.28.171:4010/src.d4e31fda.js:717:95738)
   at kl.enqueueSetState (http://183.221.28.171:4010/src.d4e31fda.js:717:47534)
   at _.prototype.setState (http://183.221.28.171:4010/src.d4e31fda.js:708:1683)
```

**Comment by russorat** [comment]
@wuststudent thank you for the issue. Please upgrade to 1.8.5.
