### ISSUE TITLE
 Chronograf (1.8.2) Invalid size returned for cell 5 of value NaN

### ISSUE THREAD

**Issue by JuanchiRios** [influxdata/chronograf#5541]
What browser are you using (name and version)?

Google Chrome | 83.0.4103.116 (Official Build) (64-bit)

What operating system are you using?
Ubuntu 18.04

Please describe what you were trying to do when you encountered this error:
querying a simple measurement with no more than 5 points. 

```
Error: Invalid size returned for cell 5 of value NaN
    at i.value (https://heavy-ee6812d0.influxcloud.net/src.9f900c48.js:2850:1411)
    at i.value (https://heavy-ee6812d0.influxcloud.net/src.9f900c48.js:2850:2700)
    at r.value (https://heavy-ee6812d0.influxcloud.net/src.9f900c48.js:2854:2359)
    at f.value (https://heavy-ee6812d0.influxcloud.net/src.9f900c48.js:2925:12908)
    at f.value (https://heavy-ee6812d0.influxcloud.net/src.9f900c48.js:2925:11170)
    at Ba (https://heavy-ee6812d0.influxcloud.net/src.9f900c48.js:717:65834)
    at ja (https://heavy-ee6812d0.influxcloud.net/src.9f900c48.js:717:65629)
    at $a (https://heavy-ee6812d0.influxcloud.net/src.9f900c48.js:717:69008)
    at oo (https://heavy-ee6812d0.influxcloud.net/src.9f900c48.js:717:91055)
    at uo (https://heavy-ee6812d0.influxcloud.net/src.9f900c48.js:717:91442)
```

**Comment by russorat** [comment]
@JuanchiRios thanks! please upgrade to the latest 1.8.5 and try again.
