### ISSUE TITLE
 Chronograf (1.8.4) Expected number or array but got string: INFO.

### ISSUE THREAD

**Issue by lxxxxxxk** [influxdata/chronograf#5559]
What browser are you using (name and version)?

What operating system are you using?

Please describe what you were trying to do when you encountered this error:

```
Error: Expected number or array but got string: INFO.
    at j (http://mon3pub.psht3.mc.ops:8888/src.bb6c33a8.js:3175:1898)
    at W.parseArray_ (http://mon3pub.psht3.mc.ops:8888/src.bb6c33a8.js:3175:31911)
    at W.start_ (http://mon3pub.psht3.mc.ops:8888/src.bb6c33a8.js:3175:35574)
    at W.updateOptions (http://mon3pub.psht3.mc.ops:8888/src.bb6c33a8.js:3175:36541)
    at d.value (http://mon3pub.psht3.mc.ops:8888/src.bb6c33a8.js:3235:4903)
    at no (http://mon3pub.psht3.mc.ops:8888/src.bb6c33a8.js:717:84207)
    at ao (http://mon3pub.psht3.mc.ops:8888/src.bb6c33a8.js:717:85725)
    at http://mon3pub.psht3.mc.ops:8888/src.bb6c33a8.js:717:98848
    at Object.exports.unstable_runWithPriority (http://mon3pub.psht3.mc.ops:8888/src.bb6c33a8.js:713:3303)
    at Xo (http://mon3pub.psht3.mc.ops:8888/src.bb6c33a8.js:717:98783)
```

**Comment by russorat** [comment]
@lxxxxxxk thanks! could you upgrade to the latest version and submit again if you see the same issue?
