### ISSUE TITLE
 Chronograf (1.8.4) Expected number or array but got string: 2020/08/19 14:08:39 Using configuration at: /etc/kapacitor/kapacitor.conf.

### ISSUE THREAD

**Issue by Shaquu** [influxdata/chronograf#5561]
### What browser are you using (name and version)?
Chrome 83.0.4103.97

### What operating system are you using?
Windows 10

### Please describe what you were trying to do when you encountered this error:
Some of my containers are sending syslog to TICK.
In chronograf Log viewer shows these logs nice and clear.
I was trying to add alert if log message contains a string but chronograf think that message field is other type then string.
![image](https://user-images.githubusercontent.com/2881159/90634402-e9108f80-e227-11ea-9558-0756074b7861.png)

```
Error: Expected number or array but got string: 2020/08/19 14:08:39 Using configuration at: /etc/kapacitor/kapacitor.conf.
    at j (http://localhost:8888/src.bb6c33a8.js:3175:1898)
    at W.parseArray_ (http://localhost:8888/src.bb6c33a8.js:3175:31911)
    at W.start_ (http://localhost:8888/src.bb6c33a8.js:3175:35574)
    at W.updateOptions (http://localhost:8888/src.bb6c33a8.js:3175:36541)
    at d.value (http://localhost:8888/src.bb6c33a8.js:3235:4903)
    at no (http://localhost:8888/src.bb6c33a8.js:717:84207)
    at ao (http://localhost:8888/src.bb6c33a8.js:717:85725)
    at http://localhost:8888/src.bb6c33a8.js:717:98848
    at Object.exports.unstable_runWithPriority (http://localhost:8888/src.bb6c33a8.js:713:3303)
    at Xo (http://localhost:8888/src.bb6c33a8.js:717:98783)
```

**Comment by sranka** [comment]
Alert Rule Builder fails since it does not support string fields (such as your `message`), only number fields are supported in the conditions and in the preview graph. As a workaround, you can create a task that uses a numerical value (such as `procid`) and then modify the generated `tickscript` with a condition that checks the `message` (using https://docs.influxdata.com/kapacitor/v1.5/tick/expr/#string-functions). You might have to dig a bit a deeper into https://docs.influxdata.com/kapacitor/v1.5 documentation in order to generate a valid and working tickscript. I would also suggest upgrading to chronograph 1.8.8 that also contains fixes for the TickScript editor.

It is a defect that the `Alert Rule Builder` let you choose fields that cannot work and crashes.
