### ISSUE TITLE
 Chronograf (1.8.4) Cannot read property 'markers' of null

### ISSUE THREAD

**Issue by wooks-pmgrow** [influxdata/chronograf#5562]
What browser are you using (name and version)?
Chrome 84.0.4147.135
What operating system are you using?
Windows 10 

Please describe what you were trying to do when you encountered this error:

```
TypeError: Cannot read property 'markers' of null
    at d.value (http://tick.monev.io:8888/src.bb6c33a8.js:3451:6586)
    at d.value (http://tick.monev.io:8888/src.bb6c33a8.js:3451:6352)
    at no (http://tick.monev.io:8888/src.bb6c33a8.js:717:84207)
    at ao (http://tick.monev.io:8888/src.bb6c33a8.js:717:85725)
    at http://tick.monev.io:8888/src.bb6c33a8.js:717:98848
    at Object.exports.unstable_runWithPriority (http://tick.monev.io:8888/src.bb6c33a8.js:713:3303)
    at Xo (http://tick.monev.io:8888/src.bb6c33a8.js:717:98783)
    at Yo (http://tick.monev.io:8888/src.bb6c33a8.js:717:98559)
    at $o (http://tick.monev.io:8888/src.bb6c33a8.js:717:97904)
    at jo (http://tick.monev.io:8888/src.bb6c33a8.js:717:96925)
```

**Comment by russorat** [comment]
@wooks-pmgrow thanks! could you upgrade to the latest version and resubmit it the issue persists?
