### ISSUE TITLE
 Chronograf (1.8.0) Invalid size returned for cell 4 of value NaN

### ISSUE THREAD

**Issue by MartinHallin** [influxdata/chronograf#5667]
What browser are you using (name and version)? Chrome Version 88.0.4324.150 (Official Build) (64-bit)

What operating system are you using? Windows 10

Please describe what you were trying to do when you encountered this error:
I clicked on new Query tab and pasted a query that worked in another tab and then clicked on submit.

    at i.value (https://metrics.<mydomain>.net/src.5692061f.js:2850:1411)
    at i.value (https://metrics.<mydomain>.net/src.5692061f.js:2850:2700)
    at r.value (https://metrics.<mydomain>.net/src.5692061f.js:2854:2359)
    at f.value (https://metrics.<mydomain>.net/src.5692061f.js:2925:12908)
    at f.value (https://metrics.<mydomain>.net/src.5692061f.js:2925:11170)
    at Ba (https://metrics.<mydomain>.net/src.5692061f.js:717:65834)
    at ja (https://metrics.<mydomain>.net/src.5692061f.js:717:65629)
    at $a (https://metrics.<mydomain>.net/src.5692061f.js:717:69008)
    at oo (https://metrics.<mydomain>.net/src.5692061f.js:717:91055)
    at uo (https://metrics.<mydomain>.net/src.5692061f.js:717:91442)

**Comment by sranka** [comment]
Thank you for reporting an issue. Pls upgrade to 1.8.10, similar errors were fixed since 1.8.0.
