### ISSUE TITLE
 Chronograf (1.8.0) - unable to retreive user list -  Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by KannappanSomu** [influxdata/chronograf#5720]
What browser are you using (name and version)? chrome 89.0.4389.114

What operating system are you using? windows

Please describe what you were trying to do when you encountered this error:

Below error is seen in chronogarf all users page , and when i click report error  link it give below logs 

![image](https://user-images.githubusercontent.com/55806176/113918709-0c9e3f80-97e3-11eb-864b-cc05359c1d4f.png)

```
TypeError: Cannot read property 'name' of undefined
    at https://metrics.volvocars.net/src.5692061f.js:4911:4187
    at Array.map (<anonymous>)
    at d.get (https://metrics.volvocars.net/src.5692061f.js:4911:4112)
    at d.value (https://metrics.volvocars.net/src.5692061f.js:4911:2697)
    at d.value (https://metrics.volvocars.net/src.5692061f.js:1913:2204)
    at Ba (https://metrics.volvocars.net/src.5692061f.js:717:65834)
    at ja (https://metrics.volvocars.net/src.5692061f.js:717:65629)
    at $a (https://metrics.volvocars.net/src.5692061f.js:717:69008)
    at oo (https://metrics.volvocars.net/src.5692061f.js:717:91055)
    at uo (https://metrics.volvocars.net/src.5692061f.js:717:91442)
```

**Comment by sranka** [comment]
Can you please try to reproduce it with 1.8.10 ? You can download it from https://portal.influxdata.com/downloads/ .

**Comment by sranka** [comment]
I inspect the code in order find the code that fails, it is: https://github.com/influxdata/chronograf/blob/661bc9d8cd89990aca552265cb631385e041e355/ui/src/admin/components/chronograf/AllUsersTableRow.tsx#L137

There is no change in this file since 1.8.0, so it is unlikely to be fixed in 1.8.10 .

**Comment by KannappanSomu** [comment]
Is this a bug ?

**Comment by sranka** [comment]
It is very likely a defect, a role references an organization that does not exist / (it is hidden). Can you please also share the InfluxDB version?

**Comment by KannappanSomu** [comment]
Its 1.8.2 

![image](https://user-images.githubusercontent.com/55806176/114377736-48d8f380-9b87-11eb-84e9-65f03c3aa87e.png)
