### ISSUE TITLE
 Chronograf (1.7.14) Invalid size returned for cell 4 of value NaN

### ISSUE THREAD

**Issue by gz198520** [influxdata/chronograf#5736]
What browser are you using (name and version)?

What operating system are you using?

Please describe what you were trying to do when you encountered this error:

```
Error: Invalid size returned for cell 4 of value NaN
    at i.value (http://39.107.141.202:8888/src.d4e31fda.js:2848:1411)
    at i.value (http://39.107.141.202:8888/src.d4e31fda.js:2848:2700)
    at r.value (http://39.107.141.202:8888/src.d4e31fda.js:2852:2359)
    at f.value (http://39.107.141.202:8888/src.d4e31fda.js:2923:12908)
    at f.value (http://39.107.141.202:8888/src.d4e31fda.js:2923:11170)
    at Ba (http://39.107.141.202:8888/src.d4e31fda.js:717:65834)
    at ja (http://39.107.141.202:8888/src.d4e31fda.js:717:65629)
    at $a (http://39.107.141.202:8888/src.d4e31fda.js:717:69008)
    at oo (http://39.107.141.202:8888/src.d4e31fda.js:717:91055)
    at uo (http://39.107.141.202:8888/src.d4e31fda.js:717:91442)
```

**Comment by sranka** [comment]
These kind of errors were fixed in 1.8 patch releases, please upgrade to the latest chronograf (1.8.10).
