### ISSUE TITLE
 Chronograf (1.8.10) Cannot read property 'queryID' of undefined

### ISSUE THREAD

**Issue by hbragib** [influxdata/chronograf#5786]
What browser are you using (name and version)?
Edge : Version 92.0.902.55 (Official build) (64-bit)

What operating system are you using?
Win 10 Pro

Please describe what you were trying to do when you encountered this error:
Accessing chronograf
```
TypeError: Cannot read property 'queryID' of undefined
    at http://serverip:8888/src.afe66dfb.js:3866:8733
    at Array.map (<anonymous>)
    at l.get (http://serverip:8888/src.afe66dfb.js:3866:8708)
    at l.value (http://serverip:8888/src.afe66dfb.js:3866:6881)
    at Ba (http://serverip:8888/src.afe66dfb.js:717:65834)
    at ja (http://serverip:8888/src.afe66dfb.js:717:65629)
    at $a (http://serverip:8888/src.afe66dfb.js:717:69008)
    at oo (http://serverip:8888/src.afe66dfb.js:717:91055)
    at uo (http://serverip:8888/src.afe66dfb.js:717:91442)
    at Yo (http://serverip:8888/src.afe66dfb.js:717:98524)
```

**Comment by sranka** [comment]
Thank you @hbragib for reporting an issue, can you pls also include your chronograf version, it appears at the bottom of the login/main page.

**Comment by hbragib** [comment]
The version is 1.8.10

**Comment by sranka** [comment]
Please upgrade to 1.9.0 and feel free to reopen if the issue is still present in the newer version.
