### ISSUE TITLE
 Chronograf (1.9.4) Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

### ISSUE THREAD

**Issue by zhanjiyong** [influxdata/chronograf#5922]
What browser are you using (name and version)?

What operating system are you using?

Please describe what you were trying to do when you encountered this error:

```
Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at _o (http://192.168.218.129:8888/src.a969287c.js:726:86672)
    at Co (http://192.168.218.129:8888/src.a969287c.js:726:86183)
    at Qu (http://192.168.218.129:8888/src.a969287c.js:726:100507)
    at exports.unstable_runWithPriority (http://192.168.218.129:8888/src.a969287c.js:722:3996)
    at ri (http://192.168.218.129:8888/src.a969287c.js:726:45696)
    at Vu (http://192.168.218.129:8888/src.a969287c.js:726:98579)
    at Cu (http://192.168.218.129:8888/src.a969287c.js:726:94635)
    at http://192.168.218.129:8888/src.a969287c.js:726:45986
    at exports.unstable_runWithPriority (http://192.168.218.129:8888/src.a969287c.js:722:3996)
    at ri (http://192.168.218.129:8888/src.a969287c.js:726:45696)
```

**Comment by sranka** [comment]
Thank you @zhanjiyong for reporting an issue, can you please also include a UI page (user context) to know better where/how it happened? Is it somehow reproducible?
