### ISSUE TITLE
 Chronograf (1.7.16) Invalid size returned for cell 7 of value NaN

### ISSUE THREAD

**Issue by mazamsezer** [influxdata/chronograf#5960]
What browser are you using (name and version)?
Opera 87.0.4390.45

What operating system are you using?
Windows 10

Please describe what you were trying to do when you encountered this error:
I was trying to pivot for last 5 minutes for a particular machine
```
Error: Invalid size returned for cell 7 of value NaN
    at i.value (http://10.0.0.71:8888/src.a5ab7481.js:2848:1411)
    at i.value (http://10.0.0.71:8888/src.a5ab7481.js:2848:2700)
    at r.value (http://10.0.0.71:8888/src.a5ab7481.js:2852:2359)
    at f.value (http://10.0.0.71:8888/src.a5ab7481.js:2923:12908)
    at f.value (http://10.0.0.71:8888/src.a5ab7481.js:2923:11170)
    at Ba (http://10.0.0.71:8888/src.a5ab7481.js:717:65834)
    at ja (http://10.0.0.71:8888/src.a5ab7481.js:717:65629)
    at $a (http://10.0.0.71:8888/src.a5ab7481.js:717:69008)
    at oo (http://10.0.0.71:8888/src.a5ab7481.js:717:91055)
    at uo (http://10.0.0.71:8888/src.a5ab7481.js:717:91442)
```

**Comment by sranka** [comment]
Thank you @mazamsezer for posting a defect. Please upgrade to the newest chronograf, this defect is fixed since chronograf 1.8.5 .
