### ISSUE TITLE
 Chronograf (1.10.0) Cannot read properties of undefined (reading 'getInstance')

### ISSUE THREAD

**Issue by JustinTArthur** [influxdata/chronograf#6007]
What browser are you using (name and version)?
Google Chrome 107.0.5304.87

What operating system are you using?
macOS

Please describe what you were trying to do when you encountered this error:
Pasting a flux query into the query builder.
```
TypeError: Cannot read properties of undefined (reading 'getInstance')
    at s.getInstance (http://[::]:8888/index.2e998595.js:107:190219)
    at s.componentDidMount (http://[::]:8888/index.2e998595.js:107:190349)
    at ws (http://[::]:8888/index.2e998595.js:1:134781)
    at Ml (http://[::]:8888/index.2e998595.js:1:152426)
    at v (http://[::]:8888/index.2e998595.js:1:172695)
    at ao (http://[::]:8888/index.2e998595.js:1:96502)
    at Al (http://[::]:8888/index.2e998595.js:1:149092)
    at bl (http://[::]:8888/index.2e998595.js:1:145246)
    at http://[::]:8888/index.2e998595.js:1:96793
    at v (http://[::]:8888/index.2e998595.js:1:172695)
```

**Comment by R290** [comment]
The error message seems identical to: https://github.com/influxdata/chronograf/issues/6009. I can replicate this issue when pasting a query using the nightly build. Both in Edge and Firefox on Windows.
