### ISSUE TITLE
 Chronograf (1.10.1) Cannot read properties of undefined (reading 'getInstance')

### ISSUE THREAD

**Issue by Safs** [influxdata/chronograf#6037]
Google Chrome

Windows 10

Try to run this querry:
`CREATE CONTINUOUS QUERY "cq_downsample_1h" ON "homeassistant"
BEGIN
  SELECT mean(*) INTO "homeassistant"."infinite".:MEASUREMENT FROM "homeassistant"."autogen"./.*/ 
  GROUP BY time(1h), *
  FILL(previous)
END`

Problem is, when use symbol " : "

```
TypeError: Cannot read properties of undefined (reading 'getInstance')
    at s.getInstance (http://homeassistant.local:8123/api/hassio_ingress/A1bTNJ5SfESP37ir6Ty01UQWNmcHWMPbi4-oj49NkWg//index.c5ba09e6.js:107:190219)
    at s.componentDidMount (http://homeassistant.local:8123/api/hassio_ingress/A1bTNJ5SfESP37ir6Ty01UQWNmcHWMPbi4-oj49NkWg//index.c5ba09e6.js:107:190349)
    at ws (http://homeassistant.local:8123/api/hassio_ingress/A1bTNJ5SfESP37ir6Ty01UQWNmcHWMPbi4-oj49NkWg//index.c5ba09e6.js:1:134781)
    at Ml (http://homeassistant.local:8123/api/hassio_ingress/A1bTNJ5SfESP37ir6Ty01UQWNmcHWMPbi4-oj49NkWg//index.c5ba09e6.js:1:152426)
    at v (http://homeassistant.local:8123/api/hassio_ingress/A1bTNJ5SfESP37ir6Ty01UQWNmcHWMPbi4-oj49NkWg//index.c5ba09e6.js:1:172695)
    at ao (http://homeassistant.local:8123/api/hassio_ingress/A1bTNJ5SfESP37ir6Ty01UQWNmcHWMPbi4-oj49NkWg//index.c5ba09e6.js:1:96502)
    at Al (http://homeassistant.local:8123/api/hassio_ingress/A1bTNJ5SfESP37ir6Ty01UQWNmcHWMPbi4-oj49NkWg//index.c5ba09e6.js:1:149092)
    at bl (http://homeassistant.local:8123/api/hassio_ingress/A1bTNJ5SfESP37ir6Ty01UQWNmcHWMPbi4-oj49NkWg//index.c5ba09e6.js:1:145246)
    at http://homeassistant.local:8123/api/hassio_ingress/A1bTNJ5SfESP37ir6Ty01UQWNmcHWMPbi4-oj49NkWg//index.c5ba09e6.js:1:96793
    at v (http://homeassistant.local:8123/api/hassio_ingress/A1bTNJ5SfESP37ir6Ty01UQWNmcHWMPbi4-oj49NkWg//index.c5ba09e6.js:1:172695)
```

**Comment by Safs** [comment]
Anybody?

**Comment by R290** [comment]
@Safs feel free to add to this topic: https://community.influxdata.com/t/is-chronograf-abandonware/28740
