### ISSUE TITLE
 Chronograf (1.10.0) Cannot read properties of undefined (reading 'getInstance')

### ISSUE THREAD

**Issue by anowinski-equinix** [influxdata/chronograf#6057]
If I try to type in (or paste) colon (:) into query in chronograf I get error message. It is regardless of the query, db structure etc - even single colon in empty line breaks the UI.

This efficiently blocks usage, as it is impossible to type in time, use typed fields, or query any id in DB that contains ':' (which is common in our solution.

What browser are you using (name and version)?
Chrome Version 116.0.5845.140 (Official Build) (arm64) (affects also safari)

What operating system are you using?
Mac OS Ventura 13.4.1 (c) 

Please describe what you were trying to do when you encountered this error:
I have typed a single ':' into explore|query field. As a result entire UI tab for the query (lower half of the interface) went blank, only with text to report the issue.

```
TypeError: Cannot read properties of undefined (reading 'getInstance')
    at s.getInstance (https://eightyeight-ca3c029e.influxcloud.net/index.e81b88ee.js:107:190219)
    at s.componentDidMount (https://eightyeight-ca3c029e.influxcloud.net/index.e81b88ee.js:107:190349)
    at ws (https://eightyeight-ca3c029e.influxcloud.net/index.e81b88ee.js:1:134781)
    at Ml (https://eightyeight-ca3c029e.influxcloud.net/index.e81b88ee.js:1:152426)
    at v (https://eightyeight-ca3c029e.influxcloud.net/index.e81b88ee.js:1:172695)
    at ao (https://eightyeight-ca3c029e.influxcloud.net/index.e81b88ee.js:1:96502)
    at Al (https://eightyeight-ca3c029e.influxcloud.net/index.e81b88ee.js:1:149092)
    at bl (https://eightyeight-ca3c029e.influxcloud.net/index.e81b88ee.js:1:145246)
    at https://eightyeight-ca3c029e.influxcloud.net/index.e81b88ee.js:1:96793
    at v (https://eightyeight-ca3c029e.influxcloud.net/index.e81b88ee.js:1:172695)
```

**Comment by ivankudibal** [comment]
this should be addressed by #6056, too
