### ISSUE TITLE
 Chronograf (1.10.1) Cannot read properties of undefined (reading 'getInstance')

### ISSUE THREAD

**Issue by liweijian199011** [influxdata/chronograf#6058]
What browser are you using (name and version)?

What operating system are you using?

Please describe what you were trying to do when you encountered this error:

```
TypeError: Cannot read properties of undefined (reading 'getInstance')
    at s.getInstance (http://122.9.145.71:18888/index.c5ba09e6.js:107:190219)
    at s.componentDidMount (http://122.9.145.71:18888/index.c5ba09e6.js:107:190349)
    at ws (http://122.9.145.71:18888/index.c5ba09e6.js:1:134781)
    at Ml (http://122.9.145.71:18888/index.c5ba09e6.js:1:152426)
    at v (http://122.9.145.71:18888/index.c5ba09e6.js:1:172695)
    at ao (http://122.9.145.71:18888/index.c5ba09e6.js:1:96502)
    at Al (http://122.9.145.71:18888/index.c5ba09e6.js:1:149092)
    at bl (http://122.9.145.71:18888/index.c5ba09e6.js:1:145246)
    at http://122.9.145.71:18888/index.c5ba09e6.js:1:96793
    at v (http://122.9.145.71:18888/index.c5ba09e6.js:1:172695)
```

**Comment by ivankudibal** [comment]
fixed by #6056, closing the issue
