### ISSUE TITLE
 Chronograf (1.10.1) Cannot read properties of undefined (reading 'getInstance')

### ISSUE THREAD

**Issue by alkissack** [influxdata/chronograf#6097]
What browser are you using (name and version)?
Opera
What operating system are you using?
WIndows 11
Please describe what you were trying to do when you encountered this error:
delete part of a query (query originally built via selector)
```
TypeError: Cannot read properties of undefined (reading 'getInstance')
    at s.getInstance (http://192.168.1.130:8889/index.c5ba09e6.js:107:190219)
    at s.componentDidMount (http://192.168.1.130:8889/index.c5ba09e6.js:107:190349)
    at ws (http://192.168.1.130:8889/index.c5ba09e6.js:1:134781)
    at Ml (http://192.168.1.130:8889/index.c5ba09e6.js:1:152426)
    at v (http://192.168.1.130:8889/index.c5ba09e6.js:1:172695)
    at ao (http://192.168.1.130:8889/index.c5ba09e6.js:1:96502)
    at Al (http://192.168.1.130:8889/index.c5ba09e6.js:1:149092)
    at bl (http://192.168.1.130:8889/index.c5ba09e6.js:1:145246)
    at http://192.168.1.130:8889/index.c5ba09e6.js:1:96793
    at v (http://192.168.1.130:8889/index.c5ba09e6.js:1:172695)
```

**Comment by R290** [comment]
@alkissack could you upgrade to v1.10.5 and check if the issue persists?
