### ISSUE TITLE
Error when accessing data after getting an empty result

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#752]
I am seeing the following error in the data explorer when running a query on a measurement that has no current data, but does have historic data.

```
app.05b1805….js:1 Uncaught TypeError: Invalid attempt to destructure non-iterable instance
    at http://localhost:8888/app.05b1805726c12e84c563.js:1:31670
    at http://localhost:8888/app.05b1805726c12e84c563.js:6:24002
    at Array.reduce (native)
    at r (http://localhost:8888/app.05b1805726c12e84c563.js:6:23958)
    at t.componentDidMount (http://localhost:8888/app.05b1805726c12e84c563.js:6:25396)
    at r.notifyAll (http://localhost:8888/vendor.a4722e96293fc3e2b7b2.js:67:610)
    at r.close (http://localhost:8888/vendor.a4722e96293fc3e2b7b2.js:194:265)
    at r.closeAll (http://localhost:8888/vendor.a4722e96293fc3e2b7b2.js:39:29439)
    at r.perform (http://localhost:8888/vendor.a4722e96293fc3e2b7b2.js:39:28883)
    at o.perform (http://localhost:8888/vendor.a4722e96293fc3e2b7b2.js:39:28800)
(anonymous) @ app.05b1805….js:1
(anonymous) @ app.05b1805….js:6
r @ app.05b1805….js:6
componentDidMount @ app.05b1805….js:6
notifyAll @ vendor.a4722e9….js:67
close @ vendor.a4722e9….js:194
closeAll @ vendor.a4722e9….js:39
perform @ vendor.a4722e9….js:39
perform @ vendor.a4722e9….js:39
perform @ vendor.a4722e9….js:38
T @ vendor.a4722e9….js:38
closeAll @ vendor.a4722e9….js:39
perform @ vendor.a4722e9….js:39
batchedUpdates @ vendor.a4722e9….js:193
i @ vendor.a4722e9….js:38
dispatchEvent @ vendor.a4722e9….js:193
app.05b1805….js:6 Uncaught (in promise) TypeError: Cannot read property 'destroy' of undefined
    at t.componentWillUnmount (app.05b1805….js:6)
    at d.unmountComponent (vendor.a4722e9….js:192)
    at Object.unmountComponent (vendor.a4722e9….js:39)
    at Object.unmountChildren (vendor.a4722e9….js:192)
    at p.unmountChildren (vendor.a4722e9….js:193)
    at p.unmountComponent (vendor.a4722e9….js:193)
    at Object.unmountComponent (vendor.a4722e9….js:39)
    at d.unmountComponent (vendor.a4722e9….js:192)
    at Object.unmountComponent (vendor.a4722e9….js:39)
    at d._updateRenderedComponent (vendor.a4722e9….js:193)
```
Oddly the graph fills in properly when first querying valid data, then switching back to the other measurement. Ask @nhaugo for a test database.

**Comment by nhaugo** [comment]
I can no longer reproduce this
